DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS wallet_transactions;
DROP TABLE IF EXISTS crypto_deposits;
DROP TABLE IF EXISTS withdrawals;
DROP TABLE IF EXISTS escrows;
DROP TABLE IF EXISTS man_profiles;
DROP TABLE IF EXISTS man_gallery;
DROP TABLE IF EXISTS man_interests;
DROP TABLE IF EXISTS woman_profiles;
DROP TABLE IF EXISTS woman_services;
DROP TABLE IF EXISTS woman_gallery;
DROP TABLE IF EXISTS woman_galleries;
DROP TABLE IF EXISTS woman_gallery_media;
DROP TABLE IF EXISTS woman_gallery_subscriptions;
DROP TABLE IF EXISTS woman_locations;
DROP TABLE IF EXISTS woman_availability;
DROP TABLE IF EXISTS booking_requests;
DROP TABLE IF EXISTS booking_date_interests;
DROP TABLE IF EXISTS video_sessions;
DROP TABLE IF EXISTS chat_rooms;
DROP TABLE IF EXISTS chat_messages;
DROP TABLE IF EXISTS kyc_requests;
DROP TABLE IF EXISTS media_items;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS ticket_messages;
DROP TABLE IF EXISTS risk_flags;
DROP TABLE IF EXISTS activity_feed;
DROP TABLE IF EXISTS revenue_daily;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS escrow_disputes;
DROP TABLE IF EXISTS provider_settings;
DROP TABLE IF EXISTS rate_limits;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS media_signed_links;
DROP TABLE IF EXISTS platform_fees;
DROP TABLE IF EXISTS user_alerts;
DROP TABLE IF EXISTS app_errors;

CREATE TABLE users (id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,full_name TEXT NOT NULL DEFAULT '',role TEXT NOT NULL CHECK(role IN ('man','woman','admin')),status TEXT NOT NULL DEFAULT 'active',verified INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE wallets (id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE,balance REAL NOT NULL DEFAULT 0,locked_balance REAL NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE wallet_transactions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,type TEXT NOT NULL,amount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'completed',note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE crypto_deposits (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,amount REAL NOT NULL,network TEXT NOT NULL DEFAULT 'USDT_TRC20',deposit_address TEXT NOT NULL,provider TEXT NOT NULL DEFAULT 'manual',provider_payment_id TEXT,provider_payment_url TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE withdrawals (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,amount REAL NOT NULL,payout_address TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',admin_note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE escrows (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,man_id TEXT NOT NULL,woman_id TEXT NOT NULL,amount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'created',released_at TEXT,refunded_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE man_profiles (id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL DEFAULT '',bio TEXT NOT NULL DEFAULT '',main_photo_url TEXT NOT NULL DEFAULT '',voice_intro_url TEXT NOT NULL DEFAULT '',video_intro_url TEXT NOT NULL DEFAULT '',date_note TEXT NOT NULL DEFAULT '',verified INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE man_gallery (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,url TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'photo',is_main INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE man_interests (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,key TEXT NOT NULL,title TEXT NOT NULL,scope TEXT NOT NULL DEFAULT 'general',created_at TEXT NOT NULL);
CREATE TABLE woman_profiles (id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL DEFAULT '',bio TEXT NOT NULL DEFAULT '',city TEXT NOT NULL DEFAULT '',public_price REAL NOT NULL DEFAULT 0,monthly_gallery_price REAL NOT NULL DEFAULT 0,minimum_offer REAL NOT NULL DEFAULT 0,cover_url TEXT NOT NULL DEFAULT '',verified INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE woman_gallery (id TEXT PRIMARY KEY,woman_id TEXT NOT NULL,url TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',price REAL NOT NULL DEFAULT 0,type TEXT NOT NULL DEFAULT 'gallery',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE woman_galleries (id TEXT PRIMARY KEY,woman_id TEXT NOT NULL,title TEXT NOT NULL DEFAULT 'Monthly Private Gallery',price REAL NOT NULL DEFAULT 0,cover_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE woman_gallery_media (id TEXT PRIMARY KEY,gallery_id TEXT NOT NULL,woman_id TEXT NOT NULL,url TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'photo',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE woman_gallery_subscriptions (id TEXT PRIMARY KEY,gallery_id TEXT NOT NULL,woman_id TEXT NOT NULL,man_id TEXT NOT NULL,amount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'active',starts_at TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE woman_services (id TEXT PRIMARY KEY,woman_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',price REAL NOT NULL DEFAULT 0,cover_url TEXT NOT NULL DEFAULT '',is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE woman_locations (id TEXT PRIMARY KEY,woman_id TEXT NOT NULL,title TEXT NOT NULL,address_hint TEXT NOT NULL DEFAULT '',date TEXT NOT NULL,time TEXT NOT NULL,cover_url TEXT NOT NULL DEFAULT '',price_modifier REAL NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE woman_availability (id TEXT PRIMARY KEY,woman_id TEXT NOT NULL,booking_type TEXT NOT NULL DEFAULT 'date' CHECK(booking_type IN ('date','chat','video_call')),date TEXT NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,duration_minutes INTEGER NOT NULL DEFAULT 60,price_override REAL NOT NULL DEFAULT 0,is_booked INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE booking_requests (id TEXT PRIMARY KEY,woman_id TEXT NOT NULL,man_id TEXT NOT NULL,availability_id TEXT NOT NULL DEFAULT '',booking_type TEXT NOT NULL DEFAULT 'date' CHECK(booking_type IN ('date','chat','video_call')),man_name TEXT NOT NULL DEFAULT '',man_photo_url TEXT NOT NULL DEFAULT '',man_note TEXT NOT NULL DEFAULT '',date TEXT NOT NULL DEFAULT '',time TEXT NOT NULL DEFAULT '',duration_minutes INTEGER NOT NULL DEFAULT 60,offer_amount REAL NOT NULL DEFAULT 0,counter_amount REAL NOT NULL DEFAULT 0,location_title TEXT NOT NULL DEFAULT '',location_hint TEXT NOT NULL DEFAULT '',services_summary TEXT NOT NULL DEFAULT '',message TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',escrow_status TEXT NOT NULL DEFAULT 'none',quality_score INTEGER NOT NULL DEFAULT 85,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE booking_date_interests (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL,key TEXT NOT NULL,title TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE video_sessions (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,room_name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ready',starts_at TEXT NOT NULL DEFAULT '',ends_at TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE chat_rooms (id TEXT PRIMARY KEY,booking_id TEXT NOT NULL UNIQUE,man_id TEXT NOT NULL,woman_id TEXT NOT NULL,man_name TEXT NOT NULL DEFAULT '',woman_name TEXT NOT NULL DEFAULT '',man_avatar_url TEXT NOT NULL DEFAULT '',woman_avatar_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'open',is_online INTEGER NOT NULL DEFAULT 1,typing_label TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE chat_messages (id TEXT PRIMARY KEY,room_id TEXT NOT NULL,sender_id TEXT NOT NULL,body TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'text',created_at TEXT NOT NULL,read_at TEXT);
CREATE TABLE kyc_requests (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,document_type TEXT NOT NULL DEFAULT 'passport',selfie_url TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',admin_note TEXT NOT NULL DEFAULT '',reviewed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE media_items (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,url TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'photo',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE tickets (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,subject TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE ticket_messages (id TEXT PRIMARY KEY,ticket_id TEXT NOT NULL,sender_id TEXT NOT NULL,message TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE risk_flags (id TEXT PRIMARY KEY,user_id TEXT,title TEXT NOT NULL,description TEXT NOT NULL,severity TEXT NOT NULL DEFAULT 'medium',status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL);
CREATE TABLE activity_feed (id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE revenue_daily (day TEXT PRIMARY KEY,amount REAL NOT NULL DEFAULT 0);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY,actor_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,metadata TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL);
CREATE TABLE escrow_disputes (id TEXT PRIMARY KEY,escrow_id TEXT NOT NULL,opened_by TEXT NOT NULL,counterparty_id TEXT NOT NULL DEFAULT '',reason TEXT NOT NULL,evidence_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'open',stage TEXT NOT NULL DEFAULT 'evidence_review',resolution TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE provider_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL DEFAULT '',is_secret INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL);
CREATE TABLE rate_limits (id TEXT PRIMARY KEY,bucket TEXT NOT NULL,ip TEXT NOT NULL,path TEXT NOT NULL,count INTEGER NOT NULL DEFAULT 0,window_start TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE sessions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL DEFAULT '',user_agent TEXT NOT NULL DEFAULT '',ip TEXT NOT NULL DEFAULT '',revoked_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE media_signed_links (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,media_id TEXT NOT NULL,signed_url TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE platform_fees (id TEXT PRIMARY KEY,escrow_id TEXT NOT NULL,amount REAL NOT NULL DEFAULT 0,fee_percent REAL NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE user_alerts (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'info',title TEXT NOT NULL,body TEXT NOT NULL DEFAULT '',target_url TEXT NOT NULL DEFAULT '',is_read INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE app_errors (id TEXT PRIMARY KEY,user_id TEXT,path TEXT NOT NULL DEFAULT '',message TEXT NOT NULL,stack TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
